#!/bin/sh

while read file
do
    case "$1" in
        "w") 
            setbg "$file" & ;;
        "r")
		    convert -rotate 90 "$file" "$file" ;;
    	"f")
	    	convert -flop "$file" "$file" ;;
        "d")
            choice=$(echo "Yes\nNo" | dmenu -i -p "delete:")
		    [ "$choice" = Yes ] && mv "$file" ~/.cache/trash && notify-send "$file deleted." ;;
    esac
done
