#! /bin/sh

sxhkd &
polybar example &
xsetroot -cursor_name left_ptr
setxkbmap pl -option caps:escape
xset r rate 300 50

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor LVDS1 -d I II III IV V
bspc monitor DP2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
