#!/bin/sh

# Stupidity of this script should be ignored till I'd come up with better solution

action=$(echo "Shutdown\nReboot\nHibernate" | dmenu -i -l 3)

[ -z $action ] && exit

case $action in
    Shutdown)
        sudo shutdown -h now
        ;;
    Reboot)
        sudo shutdown -r now
        ;;
    Hibernate)
        sudo zzz
        ;;
esac
