#!/usr/bin/bash

# Stupidity of this script should be ignored till I'd come up with better solution

action=$(printf "Shutdown computer\nReboot computer" | dmenu -i -l 2 | awk '{print $1}')

if [[ $action == 'Shutdown' ]]; then
    sudo shutdown -h now
elif [[ $action == 'Reboot' ]]; then
    sudo shutdown -r now
fi
