#!/bin/sh

laptop="LVDS-1" # laptop's screen
dmonitor="DP-2" # dock's monitor
dmonitor_connection=$(xrandr | awk '/DP-2/ {print $2}')

dock_connect() {
    if [ "$dmonitor_connection" = 'connected' ]; then
        xrandr --output "$dmonitor" --auto --primary --mode 1920x1080 --right-of "$laptop"
    else 
        xrandr --output "$laptop" --auto --primary --mode 1366x768
        xrandr --output "$dmonitor" --off
    fi
}

dock_connect
remaps
setbg
