#!/bin/bash

net() {
    net=$(cat /sys/class/net/wlp3s0/operstate)
    if [ $net == "up" ]; then
	echo "NET ON"
    elif [ $net == "down" ]; then
	echo "NET OFF"
    fi
}

music() {
    track=$(mpc current)
    [[ -n $track ]] && echo "$track ·"
}

mem() {
    mem=$(free -m | awk '/^Mem:/ {print $3}')
    echo "MEM $mem"
}

vol() {
    vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
    echo "VOL $vol"
}

bat() {
    bat=$(cat /sys/class/power_supply/BAT0/capacity)
    echo "BAT $bat"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$(( 100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

    echo "CPU $cpu"
}

tme() {
    tme=$(date "+%R")
    echo "$tme"
}

xsetroot -name "$(music) $(cpu)% · $(mem)MiB · $(bat)% · $(vol) · $(net) · $(tme) "
