#!/bin/sh

net() {
    net=$(cat /sys/class/net/wlp3s0/operstate)

    [ "$net" = "up" ] && printf "NET ON"
    [ "$net" = "down" ] && printf "NET OFF"
}

music() {
    track=$(mpc current)
    [ -n "$track" ] && printf "%s" "$track ·"
}

mem() {
    mem=$(free -m | awk '/^Mem:/ {print $3}')
    printf "MEM %s" "$mem"
}

vol() {
    vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
    printf "VOL %s" "$vol"
}

bat() {
    bat=$(cat /sys/class/power_supply/BAT0/capacity)
    printf "BAT %s" "$bat%"
}

cpu() {
    read -r cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read -r cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$(( 100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

    printf "CPU %s" "$cpu"
}

tme() {
    tme=$(date "+%R")
    printf "%s" "$tme"
}

while true; do
    xsetroot -name "$(music) $(cpu) · $(mem) · $(bat) · $(vol) · $(net) · $(tme)"
    sleep 1
done
