#!/bin/sh

# Start some useful programs and scripts
dwmstatus &
dunst &
unclutter &
xset r rate 300 50

# Start dwm in a loop, so it can be easily restarted (Mod+F5)
# And also start ssh-agent in the process
while true; do
    # No error outputs
    ssh-agent dwm >/dev/null 
done
