#!/bin/sh

laptop="LVDS-1"
monitor="DP-2"
monitor_connection=$(xrandr | awk '/DP-2/ {print $2}')

# monitor="VGA1"
# monitor_connection=$(xrandr | awk '/VGA-1/ {print $2}')

if [ "$monitor_connection" = 'connected' ]; then
    xrandr --output "$laptop" --auto
    xrandr --output "$monitor" --auto --primary --mode 1920x1080 --right-of "$laptop"

    # for a projector (mirror)
    # xrandr --output "$laptop" --auto --mode 1024x768
    # xrandr --output "$monitor" --auto --mode 1024x768 --same-as "$laptop" 

    # for a projector (two outputs)
    # xrandr --output "$laptop" --auto
    # xrandr --output "$monitor" --auto --mode 1024x768 --right-of "$laptop" 
else
    xrandr --output "$laptop" --auto --primary --mode 1366x768
    xrandr --output "$monitor" --off
fi

# set keyboard layout and wallpaper
setxkbmap pl -option caps:escape
setbg
