#!/bin/sh

# Simple script for taking screenshots with different settings using maim (entire screen, selected frame, currently active window)
# After taking a screenshot, there is a prompt asking whether screenshot should be saved and renamed

DIR="$HOME/pictures/screenshots/" # screenshots' directory
DATE="$(date +%s)" # present date to be used as a possible filename (if not changed by the user)

save_to_file() {
    xclip -selection clipboard -target image/png -out > /tmp/"$DATE.png"

    # dmenu prompt asking user whether screenshot should be save or not
    toSave=$(printf "Yes\\nNo" | dmenu -i -p "Do you want to save screenshot?")

    if [ "$toSave" = "Yes" ]; then
        changeFilename=$(printf "Yes\\nNo" | dmenu -i -p "Change filename?")

        [ "$changeFilename" = "No" ] && mv /tmp/"$DATE.png" "$DIR"
        if [ "$changeFilename" = "Yes" ]; then
            newFilename=$(printf "" | dmenu -i -p "Type new filename:")
            if [ "$newFilename" = "" ]; then 
                mv /tmp/"$DATE.png" "$DIR" 
            else
                mv /tmp/"$DATE.png" "$DIR/$newFilename.png"
            fi
        fi
    fi
}

if [ $# = 0 ]; then
    # Takes screenshot of selected area
    maim -s | xclip -selection clipboard -t image/png && save_to_file || exit 1
else
    case $1 in
        full)
            # Takes screenshot of the entire screen, saves it and then copy it to clipboard
            maim | xclip -selection clipboard -t image/png && save_to_file
            ;;
        win)
            # Takes screenshot of currently active window
            maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png && save_to_file
            ;;
        *)
            echo 'Invalid argument.'
            ;;
    esac
fi
