#!/bin/sh

mem() {
    mem=$(free -m | awk '/^Mem:/ {print $3}')
    echo "$mem"
}

vol() {
    vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
    echo  "$vol"
}

bat() {
    bat=$(cat /sys/class/power_supply/BAT0/capacity)
    echo "$bat"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$(( 100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

    echo "$cpu"
}

xsetroot -name "CPU $(cpu)% · MEM $(mem)MiB · BAT $(bat)% · VOL $(vol) · $(date "+%R")"
