#!/usr/bin/bash

net() {
    net=$(cat /sys/class/net/wlp3s0/operstate)
    if [ $net == "up" ]; then
	echo "UP"
    elif [ $net == "down" ]; then
	echo "DOWN"
    fi
}

music() {
    track=$(mpc current)
    [[ -n $track ]] && echo "$track ·"
}

mem() {
    mem=$(free -m | awk '/^Mem:/ {print $3}')
    echo "$mem"
}

vol() {
    vol=$(amixer get Master | awk -F'[][]' 'END{print $2}')
    echo  "$vol"
}

bat() {
    bat=$(cat /sys/class/power_supply/BAT0/capacity)
    echo "$bat"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$(( 100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

    echo "$cpu"
}

xsetroot -name "$(music) CPU $(cpu)% · MEM $(mem)MiB · BAT $(bat)% · VOL $(vol) · NET $(net) · $(date "+%R")"
