#!/bin/sh

up() {
    amixer set Master 5%+ unmute >/dev/null 2>&1
}

down() {
    amixer set Master 5%- unmute >/dev/null 2>&1
}

if [[ $1 == up ]]; then
    up
elif [[ $1 == down ]]; then
    down
fi
